# -*- coding: utf-8 -*-
"""Graph using Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16LXgDT1mFRu1QdQIzVIj53hciJb5pJbA

# Draw Graphs using Matplotlib

# Bar Graph
"""

import matplotlib.pyplot as plt
import numpy as np

x=['Kamal','Aju','Kuna','Kanha','Kkkk','Knk','Ajaya']
y=[12,41,20,23,25,21,58]
z=[41,52,44,28,36,65,60]
width=0.2
p=np.arange(len(x))
p1=[j+width for j in p]
color=['red','green','blue','yellow','pink','black','orange']
plt.title("Student Information")
plt.xlabel("Name Of the Students",fontsize=15,fontstyle="italic",color="r")
plt.ylabel("Age of the students",fontsize=15,fontstyle="oblique",color='orange')
plt.bar(p,y,0.2,color=color,label="Students1",linewidth=1.5)
plt.bar(p1,z,0.2,color=color,label="Students2",linewidth=1.5)
plt.xticks(p+width/2,x,rotation=10)
plt.legend(loc="upper left")
plt.show()

"""# Scatter Plot"""

#Scatter plot by matplotlib

import matplotlib.pyplot as plt
import numpy as np
x=[1,2,4,8,12,41]
y=(12,14,85,41,78,52)
color=[10,45,25,62,74,55]
sizes=[400,200,400,300,600,500]

plt.scatter(x,y,c=color, s=sizes, cmap="viridis",alpha=0.2,  edgecolor="Black", linewidth=1)
t=plt.colorbar()
t.set_label("Color Bar")
plt.show()

import pandas as pd
var=pd.DataFrame({"Name":["Kamal","Ajya","Kuna","Kanha", "Lochan","Aju"],"Age":[12,14,85,41,78,52]})
print(var)

var.insert(1, "JAva", var["Name"])
print(var)

var["Kamla"]= var["Age"][:3]
var

import pandas as pd
dis={"a":[12,14,75,78,45],"b":[74,14,12,45,52],"d":[10,12,17,18,19]}
d=pd.DataFrame(dis)
d
d.to_csv("Kamal.csv")
d

df=pd.read_csv("Kamal.csv",dtype={"b":"float"})

df

"""Histogram Plot

"""

import matplotlib.pyplot as plt
import numpy as np
import random
x=np.random.randint(10,70,(55))
x

"""# Histogram Diagram"""

var=[26, 49, 45, 46, 45, 30, 32, 42, 45, 34, 33, 31, 49, 15, 24, 17, 38,10, 32, 28, 13, 40, 25, 29, 30, 43, 14, 10, 42, 32, 29, 67, 29, 15,24, 24, 45, 31, 34, 24, 20, 30, 18, 28, 16, 27, 42, 11, 37, 65, 63,58, 59, 49, 11]
l=[10,20,30,40,50,60,70]
plt.hist(var, bins=l, edgecolor="r", bottom=10,rwidth=0.8,color='red',alpha=0.4)
plt.title("Histogram PLot")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

"""Pie plot

#Pie Chart
"""

import matplotlib.pyplot as plt
x=[10,20,30,40,50]
y=["Python","Javascript","Java","Html","Css"]
c=['r','black','pink','grey','yellow']
e=[0.3,0,0,0,0]
plt.pie(x,labels=y, explode=e,colors=c,autopct="%0.1f%%",shadow=True,startangle=20
        ,textprops={"fontsize":10})
plt.show()

plt.pie([1])
plt.show()

import matplotlib.pyplot as plt
x=[10,20,30,40,50]
x1=[40,50,30,20,10]
y=["Python","Javascript","Java","Html","Css"]
c=['r','black','pink','grey','yellow']
plt.pie(x,labels=y,colors=c)
plt.pie([1],colors='w',radius=0.8)
plt.show()

"""Steam Plot"""

import matplotlib.pyplot as plt
import numpy as np
import random
x=np.random.randint(10,60,(50))
x

"""#Stem Plot"""

import matplotlib.pyplot as plt
x=[51, 37, 10, 36, 13, 19, 49, 18, 15, 29, 38, 38, 40, 26, 46, 56, 12,20, 20, 18, 36, 20, 21, 13, 45, 27, 39, 31, 30, 39, 38, 44, 34, 27,13, 45, 19, 59, 37, 46, 30, 52, 23, 21, 18, 43, 27, 36, 23, 17]
y=[48, 34, 15, 18, 25, 46, 11, 34, 35, 27, 53, 11, 19, 49, 27, 13, 56,34, 29, 58, 26, 46, 11, 37, 13, 58, 57, 33, 14, 56, 32, 18, 49, 22,56, 47, 19, 25, 39, 49, 41, 23, 59, 57, 58, 57, 57, 50, 12, 50]

plt.stem(x,y,linefmt=":", markerfmt="*", basefmt="black")
plt.show()

"""# Box Plot"""

import matplotlib.pyplot as plt
x=[0,14,15,20,45,78]
plt.boxplot(x,vert=True)
plt.show()

# To change the Box pattern and fill the color in the box plot we use
#"notch" and "patch_artist" accordingly
plt.boxplot(x, notch=True, patch_artist=True)
plt.show()

"""#Upload File from drive in Google colab"""

from google.colab import files
import io
uploaded=files.upload()

"""# ***Functions in pnadas***"""

import pandas as pd
df=pd.read_excel("marketing_campaign.xlsx")
df

"""# **Index Function**"""

#index function.
#it help to getting information about index
df.index

"""# ***Columns Function***"""

#columns function
#it helps to know about columns
df.columns

"""# ***Replace function***"""

#Replace function is used for replace the given data
df['Dt_Customer']=df["Dt_Customer"].astype(str).str.replace("-","/")
df

#if want to replace the  value of data
import pandas as pd
df=pd.read_excel("marketing_campaign.xlsx")
df.replace(to_replace="Graduation", value="BCA")

"""# ***Rename Function***"""

#Rename function is used to change the name of data frame or columns
df.rename(columns={"Year_Birth":"Birth"},inplace=True)
df

"""# ***Describe Function***"""

#Find the Mean,Max, count or other related data
df.describe()

"""# ***head() and tail() function***"""

#head and tail function is used to show the fix amout of data
#like head() shows the value from upward
#tail() shows valus from bottom.
df.head()
#if i want to show the top 5 values then i should enter head(5)
df.head(5)

# like this tail function also use
df.tail()
#if i wnt to see the bottom 5 values then i should use tail(5)
df.tail(5)

"""# ***To show the particular range of data. Means index 1 to index 7 or index 7 to index 11 then we use string slicing method***"""

df[5:11]

"""# ***Change Data Frame into Array***"""

df.index.array

"""# ***Convert Data Frame to Numpy***"""

df.to_numpy()

"""# ***Display ascending or descending order***"""

#use ascending=False is for print it descending order
df.sort_index(axis=0,ascending=False)
df

"""#Change the data name"""

# it return a warning but change the data to python
df['Education'][0]='Python'
df

"""# Another Method to change the value. but it should not return any warning"""

df.loc[1,"Education"]="Java Script"
df

"""# To retrive particular number of data in particular column use **loc function**"""

df.loc[[4,5],["Education","Birth"]]
#iloc used to retrive particular columns
df.iloc[0,2]

"""# *Drop function used to drop the data*"""

# Drop the column
df.drop("Marital_Status", axis=1)
#drop the row
df.drop(18,axis=0)

"""# Insert and  delete Function

"""

import pandas as pd
var=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,78,9,8,65]})
var

var.insert(1,"Python",var['B'])
var

"""#Delete

"""

var.pop("B")
var

"""# Handle the missing data using Dropna & Fillna"""

import pandas as pd
df=pd.read_excel("marketing_campaign.xlsx")
df

#delete missing data row wise
df.dropna()
#drop missing daa column wise axis=0 for row and axis 1 for column
df.dropna(axis=1)

#any if drop the data if any of the data column has null values
df.dropna(how='any')
#all it delete data if all value of data table has null values
df.dropna(how='all')

#drop the value using subset
#it allow to drop the missing value from particular column
df.dropna(subset=['Education'])

#thresh
df.dropna(thresh=1)

#use fillna to fill the missing values
df.fillna("Kamal")
#it should fill the all missing values the name Kamal

from google.colab import files
import io
uploaded=files.upload()

df=pd.read_excel("Kamalexam.xlsx")
df

df.dropna(subset=["Unnamed: 1"])

df.fillna("python")

df.fillna({"Unnamed: 1":"Kamal","Unnamed: 2":"Python"})

#it fill the null value with the previous value means if
#33 number is null value row then it should be fill the value based on 32
df.fillna(method='ffill')

#it fill the null value with the foreward value means if
#33 is the null value row then it will be fill with the value of 34
df.fillna(method='bfill')

"""# Merge Function
it merge two or more data sheets and make one data sheet
"""

import pandas as pd
var1=pd.DataFrame({"A":[1,2,3,4,5,6],"B":[11,12,14,17,18,19]})
var2=pd.DataFrame({"A":[1,200,300,400,500,600],"C":[21,22,23,24,25,26]})
pd.merge(var1,var2,on="A",how="left",indicator=True)

pd.merge(var1,var2,left_index=True, right_index=True)

"""# Concat
it also use to merge two data series
"""

var=pd.Series([1,2,3,4])
var2=pd.Series([5,8,9,6])
pd.concat([var,var2])

x=int(input("Enter a number: "))
y=int(input("Enter a number: "))
while(x%y==0):
  if(x>y):
    # if(x%y==0):
    #   print("Gcd is :",y)
    # else:
      r=x%y
      x=y
      y=r
  else:
    r=y%x
    x=y
    y=r
  print("Gcd is ",y)